config:
  prefix: "&7[ZM] &r"
  head: "&bWhat are you going to do? &7(&r» &7- &rhover&7, &rclick&7)"
  find: "» &bLook for a free place."
  find_hover: "&b/zone find"
  create: "» &bCreate a new zone."
  create_hover: "&b/zone create"
  subcreate: "» &bCreate a new subzone."
  subcreate_hover: "&b/zone subcreate <Zone>"
  list: "» &bList all your zones."
  list_hover: "&b/zone list"
  cancel: "» &bCancel creation."
  cancel_hover: "&b/zone cancel"
  addmember: "» &bAdd a player to a zone."
  addmember_hover: "&b/zone addmember <Zone> <Player>"
  removemember: "» &bRemove a player from a zone."
  removemember_hover: "&b/zone removemember <Zone> <Player>"
  flag: "» &bModify a flag of a zone."
  flag_hover: "&b/zone flag <Zone> <Flag> <Flagvalue>"
  info: "» &bGet information about a zone."
  info_hover: "&b/zone info <Zone>"
  delete: "» &bDelete a zone."
  delete_hover: "&b/zone delete <Zone>"
  zone_find: "&bUse the stick to look for a free place by &7left-&b and &7right-click&b."
  zone_create_sign: "&bUse the stick to sign the &5first &bpoint by &7left- &band the &dsecond &bpoint by &7right-click&b."
  zone_create_not_signed: "&cZone not signed."
  zone_create_length_min: 10
  zone_create_length_max: 100
  zone_create_width_min: 10
  zone_create_width_max: 100
  zone_create_width_length_error: "&cZone must be at least &7{0}x{1} &cblocks and &7{2}x{3}&c maximum."
  zone_create_area_min: 100
  zone_create_area_max: 10000
  zone_create_area_under: "&cMinimum area: &7{0}"
  zone_create_area_over: "&cMaximum area: &7{0}"
  zone_create_have_max: 5
  zone_create_have_over_equal: "&cYou are already having &7{count}&c (out of &7{zone_create_have_max}&c) zone(s) in this world."
  zone_create_area_max_claimable: 10000
  zone_create_area_max_claimable_over: "&cYou are already having an area of &7{area}&c block(s) spread over &7{count}&c zone(s)."
  zone_create_overlaps_unowned: "&cZone overlaps with one or more unowned zones."
  zone_create_priority: 1
  zone_create: "&aZone &7{0} &acreated."
  zone_subcreate_sign: "&bUse the stick to sign the first point by &7left- &band the second point by &7right-click&b."
  zone_subcreate_not_in_zone: "&cSubzone is not completely in zone &7{0}ca."
  zone_subcreate_circular: "&cThere was a circular inheritance exception."
  zone_subcreate: "&aSubzone &7{0} &acreated."
  zone_cancel_not_running: "&cZone creation not running."
  zone_cancel: "&bZone creation cancelled."
  zone_list: "&bList of all your zones: &7{list}"
  zone_addmember_not_existing: "&7{0} &cdoes not exist."
  zone_addmember_already_member: "&7{0} &cis already a member at zone &7{1}."
  zone_addmember: "&7{0} &ais now a member of zone &7{1}."
  zone_removemember_unknownplayer: "&7{0} &cis not a member at zone &7{1}."
  zone_removemember: "&7{0} &ais no longer a member at zone &7{1}."
  zone_flag_not_found: "&cFlag &7{0} &cdoes not exist."
  zone_flag_changed: "&aFlag &7{0} &aat zone &7{1} &achanged to &7{2}&a."
  zone_info_id: "&bName: &7{id}"
  zone_info_priority: "&bPriority: &7"
  zone_info_parent: "&bParent: &7"
  zone_info_owners: "&bOwners: &7"
  zone_info_members: "&bMembers: &7"
  zone_info_flag: "&bFlag: &7{0} &b- Flagvalue: &7{1}"
  zone_info_start: "&5Starting &bpoint: &7X: {0} &b/ &7Z: {1}"
  zone_info_end: "&dEnding &bpoint: &7X: {0} &b/ &7Z: {1}"
  zone_info_area: "&bArea: &7{0}"
  zone_delete: "&aZone &7{0} &adeleted."
  zone_select: "&aZone &7{0} &aselected."
  event_find_multi: "&bZones found: &7{ids}"
  event_find_no: "&cNo zones found."
  event_find: "&bZone found: &7{ids}"
  event_sign_first: "&5First &bposition marked."
  event_sign_second: "&dSecond &bposition marked."
  event_sign_area: " &bArea: &7{0}"
  wait_message: "&bPlease wait ..."
  no_zone: "&cYou do not have a zone in this world."
  not_exisiting_zone: "&cZone &7{0} &cdoes not exist."
  usage_message: "&cUsage: &7{0}"
  permission_message: "&cLacking permission: &7{0}"
  not_a_player_message: "&cNot a player?"
  update_available: "&bAn update is available at &7{0}&b."
  no_update_available: "&bYou are running the latest version."
  update_error: "&cError during update check."